import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

const Container = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJS - billyjacoby</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <h1>Heading</h1>
      </Container>

      <footer></footer>
    </div>
  );
}
